# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='pylsr',
    version='2020',
    description="Use this module to read, and write to Apple's Layer Source Representation (LSR) Image format.",
    python_requires='==3.*,>=3.5.0',
    project_urls={
        "documentation":
            "https://github.com/FHPythonUtils/PyLSR/blob/master/README.md",
        "homepage":
            "https://github.com/FHPythonUtils/PyLSR",
        "repository":
            "https://github.com/FHPythonUtils/PyLSR"
    },
    author='FredHappyface',
    classifiers=[
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Operating System :: OS Independent'
    ],
    packages=['pylsr'],
    package_dir={"": "."},
    package_data={},
    install_requires=['pillow==7.*,>=7.1.2'],
)
